apiVersion: v1
kind: Pod
metadata:
  name: constraints-cpu-demo
  namespace: soft-multitenancy-check
spec:
  containers:
  - name: constraints-cpu-demo-ctr
    image: nginx
    resources:
      limits:
        cpu: "800M"
        memory: 256Mi
      requests:
        cpu: "100m"
        memory: 50Mi
